version: 2
updates:
  # npm dependencies with PR grouping and security updates
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 15
    # Group related dependencies to reduce PR noise
    groups:
      # Development dependencies
      development-dependencies:
        patterns:
          - '@types/*'
          - 'eslint*'
          - 'prettier'
          - 'typescript'
          - '@eslint/*'
        update-types:
          - 'minor'
          - 'patch'
      # React/Next.js ecosystem
      react-ecosystem:
        patterns:
          - 'react*'
          - 'next'
          - '@next/*'
          - 'eslint-config-next'
        update-types:
          - 'minor'
          - 'patch'
      # UI libraries
      ui-libraries:
        patterns:
          - '@radix-ui/*'
          - 'framer-motion'
          - 'tailwindcss'
          - '@tailwindcss/*'
        update-types:
          - 'minor'
          - 'patch'
      # Utility libraries
      utilities:
        patterns:
          - 'clsx'
          - 'exifr'
          - 'react-dropzone'
          - 'zustand'
        update-types:
          - 'minor'
          - 'patch'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore(dev)'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automated'

  # GitHub Actions dependencies
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 5
    # Group GitHub Actions updates
    groups:
      github-actions:
        patterns:
          - 'actions/*'
          - '*'
        update-types:
          - 'major'
          - 'minor'
          - 'patch'
    commit-message:
      prefix: 'ci'
      include: 'scope'
    labels:
      - 'ci'
      - 'github-actions'
      - 'automated'
