name = "metamark"
compatibility_date = "2025-08-31"
main = "src/worker.ts"

[assets]
directory = "dist"
binding = "ASSETS"
html_handling = "force-trailing-slash"

[[routes]]
pattern = "metamark.kiakiraki.dev"
custom_domain = true

[env.preview]
# Inherit top-level settings; no custom domain for preview (uses workers.dev)
